server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mercadolivre
    username: keycloak
    password: keycloak
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
