server:
  port: 8080

spring:
  application:
    name: mercado-livre
    
  datasource:
    url: jdbc:postgresql://localhost:5432/mercadolivre
    username: keycloak
    password: keycloak
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 40
      idle-timeout: 10000
      auto-commit: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
      
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always